Repository EPITECH-Strasbourg-2021/CPP-Arcade-Spec, pull requests merged in 2018-03, with the labels that each got.

#1 Correct English syntax
  README.md
Labels: enhancement

#2 Change Vect to a templated type
  README.md
Labels: enhancement

#9 [+] getName
  IGameModule.hpp
  IGraphicLib.hpp
Labels: enhancement

#11 Adding a refresh method for IGraphicLib
  IGraphicLib.hpp
Labels: enhancement

#10 [+] entryPoint (Fix #6)
  README.md
  entryPoint.cpp
Labels: enhancement

#13 Adding NONE to the Keys enum
  Keys.hpp
Labels: help wanted

#16 Allow for non-uniform PixelBoxes + Refactoring
  PixelBox.hpp
Labels: help wanted

#20 Major changes in IGameModule (renommed in IGameLib)
  IGameLib.hpp
  IGameModule.hpp
  README.md
Labels: enhancement

#25 Removed constructors in interfaces + Stricter constness
  IGameLib.hpp
  IGraphicLib.hpp
Labels: Syntax, enhancement

#26 Added default destructor to TextBox
  TextBox.hpp
Labels: Syntax, enhancement

#39 QoL changes on TextBox
  PixelBox.hpp
  TextBox.hpp
Labels: Syntax

#41 Added const to PixelBox::getPixel() method.
  PixelBox.hpp
Labels: Syntax

#40 Adding color filling upon construction of PixelBox
  PixelBox.hpp
Labels: enhancement

#42 Adding a cast override from Arcade::Color to unsigned char *
  Color.hpp
Labels: Syntax, enhancement

#43 Adding PixelBox::putRect() method
  PixelBox.hpp
Labels: enhancement

#44 Removing initRenderer() and stopRenderer() from IGraphicLib + Refactoring
  IGraphicLib.hpp
Labels: Syntax

#47 Added Event Handling documentation for IGraphicLib
  IGraphicLib.hpp
Labels: Syntax

#50 [-] Remove shady std::hash
  Vect.hpp
Labels: Syntax

#53 Cancel PR #51, implementation prohibited
  IGraphicLib.hpp
Labels: debate

#58 Separating game logic from event handling + Fix #57
  IGameLib.hpp
Labels: enhancement

#60 Adding overloaded operators to Arcade::Vect
  Vect.hpp
Labels: Syntax, enhancement
