Repository EPITECH-Strasbourg-2021/CPP-Arcade-Spec, pull requests merged in 2018-04, with the labels that each got.

#61 [-] Return reference in getName
  IGameLib.hpp
Labels: Syntax

#63 [~] change to reference
  IGameLib.hpp
Labels: Syntax

#64 Adding Arcade::Color::operator==
  Color.hpp
Labels: Syntax, enhancement

#65 Add Player name setter
  IGameLib.hpp
Labels: enhancement

#66 [+] getScore
  IGameLib.hpp
Labels: enhancement

#68 [~] return bool
  IGameLib.hpp
Labels: Syntax, enhancement

#70 [-] remove useless func
  IGameLib.hpp
Labels: Syntax

#72 Documentation in Doxygen format
  Color.hpp
  IGameLib.hpp
  IGraphicLib.hpp
  Keys.hpp
  PixelBox.hpp
  TextBox.hpp
  Vect.hpp
Labels: Documentation
